name: push main - Build & Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: build, tag & push Docker image
        uses: olehkrupko/actions/docker-build-push@main
        with:
          image-name: ${{ github.repository }}
          is-latest: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
