name: Push main - package Docker image
run-name: Push main - package Docker image for ${{ github.ref_name }}

on:
  push:
    branches:
      - main

jobs:
  python-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: build, tag & push Docker image
        uses: olehkrupko/actions/python-docker@main
        with:
          image-name: ${{ github.repository }}
          is-latest: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
