name: PR main - Build & Push Docker image

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: build, tag & push Docker image
        uses: olehkrupko/actions/docker-build-push@main
        with:
          image-name: ${{ github.repository }}
          is-latest: false
          pr-number: ${{ github.event.pull_request.number }}
          milestone-number: ${{ github.event.pull_request.milestone.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
