name: push-prod
run-name: Push update to PROD from ${{ github.ref_name }}
on:
  push:
    branches:
      - 'main'
      - '87-testing-black'
  # pull_request:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{github.job}}
