name: push-deploy
run-name: Deploy update from ${{ github.ref_name }}
on:
  push:
    branches:
      - 'main'
      - '27-python-map-reduce-filter-zip'
jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ${{github.job}}
