name: scheduled-parsing
run-name: Scheduled parsing initiated by adding feeds to queue
on:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  data_parsing:
    runs-on: self-hosted
    steps:
      - name: Send request and save status code
        run: echo "status_code=`curl --write-out '%{http_code}' --silent --output /dev/null -X PUT 'http://192.168.0.155:30010/feeds/parse/queue'`" >> "$GITHUB_ENV"
      - name: Print status
        run: echo "$status_code"
      - name: Check request status
        run: if ([[ "$status_code" == 200 ]]); then exit 0; else echo "$status_code"; exit 1; fi
